### ISSUE TITLE
No such file or directory: 'Hg_Prediction_tables/tree.json'

### ISSUE THREAD

**Issue by npsonis** [genid/Yleaf#10]
Hi I had installed and using a previous version.

I updated to 3.0 and now I get the following error:
[mpileup] 1 samples in 1 input files
--- 0.20 seconds in run PileUp ---
Extracting haplogroups...
Traceback (most recent call last):
  File "/home/psonis/software/Yleaf/Yleaf.py", line 587, in <module>
    main()
  File "/home/psonis/software/Yleaf/Yleaf.py", line 561, in main
    output_file = samtools(args.threads, folder, folder_name, bam_file, args.Quality_thresh,
  File "/home/psonis/software/Yleaf/Yleaf.py", line 454, in samtools
    extract_haplogroups(markerfile, args.Reads_thresh, args.Base_majority,
  File "/home/psonis/software/Yleaf/Yleaf.py", line 413, in extract_haplogroups
    tree = Tree("Hg_Prediction_tables/tree.json")
  File "/home/psonis/software/Yleaf/tree.py", line 33, in __init__
    self._construct_tree(file)
  File "/home/psonis/software/Yleaf/tree.py", line 41, in _construct_tree
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Hg_Prediction_tables/tree.json'

Where is this file?

Also, I updated to 3.01 and everything is different. Not sure which is the executable, which are the proper files to use...
when testing python yleaf/Yleaf.py I get 
Traceback (most recent call last):
  File "/home/psonis/software/Yleaf/yleaf/Yleaf.py", line 30, in <module>
    from yleaf import __version__
ModuleNotFoundError: No module named 'yleaf'

**Comment by bramvanwersch** [comment]
Hello npsonis,
Thank you for using Yleaf. I am not sure why the tree.json file is missing but you can download it from the official 3.0.1 release. You can find that here: https://github.com/genid/Yleaf/releases/tag/3.0.1 . 

I think you downloaded the 3.1 version afterwards which is still under development and might have some issues. This is the version you will get when cloning the repository at the moment. The provided manual is not yet updated to reflect the changes in this new version. For this new version you should run pip install . in the folder containing the setup.py. That will fix the issue for now.

Let me know if you have any issues.

**Comment by npsonis** [comment]
Hi again,
I just re-installed 3.0.1 (zip file) (not 3.1 with git clone) The tree.json is in the Hg_Prediction_tables directory. However, according to the log bellow

File "/home/psonis/software/Yleaf/tree.py", line 41, in _construct_tree
with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Hg_Prediction_tables/tree.json'

I think the problem is that the tree.py cannot find the tree.json. I don't know why, though.

**Comment by bramvanwersch** [comment]
Hmm, that is a strange issue. I have tested it myself real quick and I seem to be able to get the prediction and locate the tree.json file. I suspect that something is messing with the working directory and that the relative defined path is pointing the wrong way. If you have some experience with python you could modify the Yleaf.py file and change line 413 from:
`tree = Tree("Hg_Prediction_tables/tree.json")` into
`tree = Tree("/home/psonis/software/Yleaf/yleaf/Hg_Prediction_tables/tree.json")`
given that Yleaf is in that folder. This will then only work specifically for you but circumvent the relative path.

Alternatively you could use version 3.1 by git cloning the repository and running  `pip install .` After that you should be able to call Yleaf with using `Yleaf` followed by the rest of the arguments. I suspect you will not have this issue in the new version since some things have changed with how paths are defined.

**Comment by npsonis** [comment]
So the first solution did not work, unfortunatelly. I still get the same message.

Solution 2 gives me the following (after pip install .) when I run the executable: Yleaf (which is in my PATH):
Traceback (most recent call last):
  File "/home/psonis/.local/bin/Yleaf", line 5, in <module>
    from yleaf.Yleaf import main
ModuleNotFoundError: No module named 'yleaf'

**Comment by bramvanwersch** [comment]
My apologies. I was working on the setup.py yesterday and due to some circumstances I had to do something else and I had left it in a broken state. I have now quickly changed this and verified that I can properly install and use it myself. Could you try to first run `pip uninstall yleaf` and then after recloning Yleaf run `pip install .` again. 

Again my apologies.

**Comment by npsonis** [comment]
Thanks. Yleaf works now. I changed the command in order to work with the new arguments (-o, -rg) and I get the Hg prediction. I still had to provide the path for the predict_haplogroup.py and execute it with python.

One note though, for the first time the program needs to download the ref (in my case hg19). Does it store it somewhere (this will take space) or it generates some files that are needed and then it is removed? Why not providing our own ref path? Or why not downloading just the Y.chr?

Sorry for the questions, they are unrelated to the issue. You may close this now.

**Comment by bramvanwersch** [comment]
I am happy to hear that it is working now.

The file is downloaded at your pip install location. We will need the full file so it takes around 3gb of storage. I agree it is not ideal and I think that providing a custom reference or at least the ability to specify the path would be a good addition. When uninstalling the file will be removed again, so you dont have to worry about that. We download the full reference because of the fastq option that will need a full reference genome in order for the most accurate results. Since a decent number of people do not use this option it is probably best to only download the y-chr data when using bam input files. 

Thank you for the feedback and raising your concerns.
